authors:
  taylorsilva:
    name: Taylor Silva
    description: Maintainer
    avatar: https://github.com/taylorsilva.png
  ruiva:
    name: Rui Yang
    description: Former Maintainer
    avatar: https://media.licdn.com/dms/image/v2/C5603AQFGY-Hm8Jc0KA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1516549738550?e=1768435200&v=beta&t=IaL-Vw8XKj6DmgutxS3xOu411bEUgRZIIXmdiwl8rew