authors:
  tsilva:
    name: Taylor Silva
    description: Lead Maintainer
    avatar: https://github.com/taylorsilva.png
  kumper:
    name: Kalin
    description: Contributor
    avatar: https://github.com/Kump3r.png
  jamesma:
    name: James Ma
    description: Former Product Manager
    avatar: https://github.com/jama22.png
  tbullock:
    name: Topher Bullock
    description: Former Editor
    avatar: https://github.com/topherbullock.png
  lauchinachie:
    name: Lindsay Auchinachie
    description: Former Product Designer
    avatar: https://github.com/Lindsayauchin.png
  asuraci:
    name: Alex Suraci
    description: Former Maintainer
    avatar: https://github.com/vito.png
  sfoerster:
    name: Scott Foerster
    description: Former Product Manager
    avatar: https://github.com/scottietremendous
  dforde:
    name: Dwayne Forde
    description: Former Pivotal Director of Engineering
    avatar: https://github.com/osis.png
  jwinters:
    name: Joshua Winters
    description: Former Developer
    avatar: https://github.com/jwinters.png
  sreddy:
    name: Shashwathi Reddy
    description: Former Developer
    avatar: https://miro.medium.com/v2/resize:fill:176:176/1*UyL2svGIixMjkLcakEweSg@2x.jpeg
  speinado:
    name: Sam Peinado
    description: Former Product Designer
    avatar: https://miro.medium.com/v2/resize:fill:176:176/2*PueUUrdy9MHlIPE4PlVG2Q.jpeg
  saman:
    name: Saman
    description: Former Developer
    avatar: https://miro.medium.com/v2/resize:fill:176:176/1*j203XDYKr71dIrnlheGLsA.jpeg
  jghiloni:
    name: Josh Ghiloni
    description: Former Advisory Solutions Architect
    avatar: https://avatars.githubusercontent.com/u/1834264?v=4
  jklassen:
    name: Jamie Klassen
    description: Former Developer
    avatar: https://github.com/jamieklassen.png