authors:
  tsilva:
    name: Taylor Silva
    description: Maintainer
    avatar: https://github.com/taylorsilva.png
  jamesma:
    name: James Ma
    description: Former Product Manager
    avatar: https://miro.medium.com/v2/resize:fill:176:176/2*5LAj0RMtEpmKoWu5JZ_izg.jpeg
  tbullock:
    name: Topher Bullock
    description: Former Editor
    avatar: https://miro.medium.com/v2/resize:fill:176:176/1*lqzgDf65Rxt1KV0FkoK3YQ.jpeg
  lauchinachie:
    name: Lindsay Auchinachie
    description: Former Product Designer
    avatar: https://miro.medium.com/v2/resize:fill:176:176/1*mlen1LB-MqZKkj5PdMAQ_Q@2x.jpeg
