#!/bin/bash

set -e -u

cd $(dirname $0)/..

go install github.com/vito/booklit/cmd/booklit

booklit -i lit/index.lit -o . \
  --save-search-index \
  --html-templates html/ \
  --plugin github.com/concourse/docs/src/concourse-lit/splash \
  --plugin github.com/concourse/docs/src/concourse-lit/resources-table \
  --plugin github.com/concourse/docs/src/concourse-lit/docs \
  --plugin github.com/concourse/docs/src/concourse-lit/community "$@"
