#!/bin/bash

set -e -x

git config --global user.email "concourseteam+concourse-github-bot@gmail.com"
git config --global user.name "Concourse Bot"

# Change to the docs repo
pushd docs
  if [ -e .git ] && git remote | grep origin >/dev/null; then
    # undo single-branch clone and fetch gh-pages
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    git fetch origin gh-pages

    ref=$(git rev-parse HEAD)
  fi

  # Install dependencies
  pip install zensical nodeenv
  nodeenv env --node=22.21.1
  npm ci

  # Create site directory
  npm run build

  # Copy well-known for BlueSky
  cp .well-known site/.well-known

  if [ -e .git ]; then
    git checkout --orphan gh-pages
    git rm -rf .

    mv site/* .
    rmdir site

    git add -A
    git commit --allow-empty -m "build"
  fi
popd
