---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: 3.14-alpine3.21

inputs:
  - name: docs

outputs:
  - name: built-docs
    path: docs

params:
  ANALYTICS_ID:
  GITHUB_TOKEN:

run:
  path: docs/ci/build
