---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cgr.dev/chainguard/python
    tag: latest-dev

inputs:
  - name: docs
  - name: examples
    path: docs/libs/examples
    optional: true

outputs:
  - name: built-docs
    path: docs

run:
  path: docs/ci/build
  user: root #needed for the chainguard python image
