---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: python
    tag: 3.14-alpine

inputs:
  - name: docs
  - name: examples
    path: docs/libs/examples
    optional: true

outputs:
  - name: built-docs
    path: docs

params:
  ANALYTICS_ID:
  GITHUB_TOKEN:

run:
  path: docs/ci/build
