#!/bin/bash

set -e

apk add --no-progress git gcc ytt

git config --global user.email "concourseteam+concourse-github-bot@gmail.com"
git config --global user.name "Concourse Bot"

pushd docs
  pip install mkdocs-material mkdocs-redirects mkdocs-glightbox nodeenv
  nodeenv env --node=22.21.1

  source env/bin/activate

  npm ci

  # Remove apps before build
  rm -rf docs/libs/examples/apps/
  rm -rf docs/libs/examples/**/*.md

  # Create site directory
  npm run build

  # Copy well-known for BlueSky
  cp -R .well-known site/.well-known

  if [ -e .git ]; then
    git checkout gh-pages
    git rm -rf .

    rm -rf venv/ node_modules/ env/ .cache/ overrides/ docs/ .idea/

    mv site/{.,}* .
    rmdir site

    echo -n "concourse-ci.org" > CNAME

    echo "User-agent: *" > robots.txt
    echo -n "Disallow: /single-page.html" >> robots.txt

    # Tells Github to publish immediately and skip it's automatic build step
    touch .nojekyll

    # avoid committing submodule
    git rm --cached ./libs/examples
    git add -A
    git commit --allow-empty -m "build"
  fi
popd
